disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Blog"

[params]
displayName = "English"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
author = { name = "Tomohiro Kobayashi", headline = "Hi!" }
